/* ==========================================================================
   Shared logic used by app.js:
   - reading/writing data/projects.json (the CRUD source of truth)
   - regenerating js/data.js (the plain static file the deployed site reads)

   You should never need to run this by hand — app.js calls it automatically
   after every create/update/delete/reorder.
   ========================================================================== */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const PROJECTS_JSON = path.join(ROOT, "data", "projects.json");
const DATA_JS = path.join(ROOT, "js", "data.js");

/* ---------- id helpers ---------- */
function slugify(title) {
  return String(title || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "project";
}

function uniqueId(title, projects, ignoreId) {
  const base = slugify(title);
  const taken = new Set(
    projects.filter((p) => p.id !== ignoreId).map((p) => p.id)
  );
  if (!taken.has(base)) return base;
  let i = 2;
  while (taken.has(`${base}-${i}`)) i++;
  return `${base}-${i}`;
}

/* ---------- read / write projects.json ---------- */
function readProjects() {
  if (!fs.existsSync(PROJECTS_JSON)) return [];
  const raw = fs.readFileSync(PROJECTS_JSON, "utf8").trim();
  return raw ? JSON.parse(raw) : [];
}

function writeProjects(projects) {
  fs.mkdirSync(path.dirname(PROJECTS_JSON), { recursive: true });
  fs.writeFileSync(PROJECTS_JSON, JSON.stringify(projects, null, 2) + "\n");
  regenerateDataJs(projects);
}

/* ---------- regenerate the static js/data.js ---------- */
function regenerateDataJs(projects) {
  // Filter chips above the grid are derived automatically from whatever
  // categories the projects actually use, so they never fall out of sync.
  const categories = [];
  projects.forEach((p) => {
    (p.categories || []).forEach((c) => {
      if (!categories.includes(c)) categories.push(c);
    });
  });
  const filters = ["All", ...categories];

  const banner = `/* ==========================================================================
   Project data — AUTO-GENERATED by app.js from data/projects.json.

   Don't hand-edit this file: run \`node app.js\` and use the admin UI at
   http://localhost:PORT/admin to add, edit, reorder or delete projects.
   Every change there rewrites this file for you.
   ========================================================================== */

`;

  const body =
    `const PROJECTS = ${JSON.stringify(projects, null, 2)};\n\n` +
    `/* Filter buttons shown above the grid — derived from each project's \`categories\`. */\n` +
    `const FILTERS = ${JSON.stringify(filters)};\n`;

  fs.mkdirSync(path.dirname(DATA_JS), { recursive: true });
  fs.writeFileSync(DATA_JS, banner + body);
}

module.exports = {
  ROOT,
  PROJECTS_JSON,
  DATA_JS,
  slugify,
  uniqueId,
  readProjects,
  writeProjects,
  regenerateDataJs,
};
